trial: 1
c_val: 1.0
hours: 1
sa_threshold: 10.
expansion_threshold: 0.995
use_lipinski_filter: False
radical_check: True
simulation_num: 3
use_hashimoto_filter: False
model_json: model/model2.tf25.json
model_weight: model/model2.tf25.best.ckpt.h5
output_dir: result/example02
reward_calculator: reward.logP_reward
